### ISSUE TITLE
Y axis outside window.

### ISSUE THREAD

**Issue by ghayne** [mblackstock/node-red-contrib-data-view#3]
On Opera running on Linux I get:
![image](https://user-images.githubusercontent.com/29737866/103170112-ae53df00-4839-11eb-8969-2526ab6a6af3.png)

[EDIT - The same on Chrome]

**Comment by mblackstock** [comment]
Thanks, yes, I probably need to adjust the margins a bit, maybe dynamically

**Comment by mblackstock** [comment]
fixed on develop

**Comment by ghayne** [comment]
Still happening occasionally 0.0.2:
![image](https://user-images.githubusercontent.com/29737866/103463389-e5d3f700-4d23-11eb-942a-d6eebee76677.png)

**Comment by mblackstock** [comment]
thanks.  will have another look!

**Comment by mblackstock** [comment]
I'm having trouble reproducing the problem with the latest rev.  Any pointers on how to reproduce it would be appreciated.

**Comment by Paul-Reed** [comment]
I also can't reproduce here with current rev, it appears correctly formatted for me now.
...maybe browser caching issue??

**Comment by ghayne** [comment]
Looks like it was the cache as Paul suggested. Apologies for wasting your time!

**Comment by mblackstock** [comment]
👍   no worries! thanks for letting me know.
